import Head from 'next/head';
import { Flex, Text, useDisclosure } from '@chakra-ui/react';
import { HiMenuAlt2 } from 'react-icons/hi';
import { IoFilterSharp } from 'react-icons/io5';
import Sidebar from '@/components/sidebar';

export default function Home() {
  const { isOpen, onOpen, onClose } = useDisclosure();
  return (
    <>
      <Head>
        <title>Award App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex justifyContent="space-between" alignItems="center" p={5}>
        <HiMenuAlt2 size="20px" onClick={onOpen} cursor="pointer" />
        <Text fontSize="lg" fontWeight="bold">
          Awards
        </Text>
        <IoFilterSharp size="20px" />
      </Flex>
      <Sidebar isOpen={isOpen} onClose={onClose} />
    </>
  );
}
